package com.example.a41ptaskmanager;

import java.util.Date;

public class TaskModel {
    public static final int TASK_ROW_WIDTH = 20;
    private int id;
    private String name;
    private String description;
    private String dueDate;
    private boolean isComplete;

    // Constructors
    // Default constructor for new task. No ID passed - this is generated by DB - and set to
    // incomplete by default.
    public TaskModel(String name, String description, String dueDate) {
        this.name = name;
        this.description = description;
        this.dueDate = dueDate;
        this.isComplete = false;
    }
    // Constructor for retrieving existing tasks from DB and adding them to a TaskModel object
    public TaskModel(int id, String name, String description, String dueDate, boolean isComplete) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.dueDate = dueDate;
        this.isComplete = isComplete;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public boolean isComplete() {
        return isComplete;
    }

    public void setComplete(boolean complete) {
        isComplete = complete;
    }

    // Other methods
    public String toString() {
        return name + "\n" + "Due: " + dueDate + " | Complete: " + isComplete;
    }
}
